language: generic
sudo: required
services:
    - docker
before_install::
    - docker build -t mango/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true mango/docker-react npm run test
